trigger:
- main  # Adjust based on your branch

variables:
  azureServiceConnection: 'e03612ce-bd7c-4557-ae2f-f1ee8f720fa3'  # Replace with your Azure service connection ID
  subscriptionId: '51f41f85-b52c-4d95-a2f5-28303cbdb6ec'           # Replace with your Azure subscription ID
  resourceGroupName: 'adq-appdeploy-rg'                               # Replace with your Resource Group name
  location: 'Central US'                                              # Replace with your Azure region
  vnetTemplateFile: 'modules/vnet/vnet.json'                                    # Path to VNet ARM template file
  vnetParametersFile: 'modules/vnet/vnet.parameters.json'                       # Path to VNet parameters file
  appMachineTemplateFile: 'modules/machines/appvm/app.machine.json'                                      # Path to appMachine ARM template file
  appMachineParametersFile: 'modules/machines/appvm/app.machine.parameters.json'                         # Path to appMachine parameters file
  bastionTemplateFile: 'modules/bastion/bastion.json'                                  # Path to Bastion ARM template file
  bastionParametersFile: 'modules/bastion/bastion.parameters.json'                     # Path to Bastion parameters file
  sqlTemplateFile: 'modules/machines/sqlvm/sql.machine.json'                                  # Path to sql ARM template file
  sqlParametersFile: 'modules/machines/sqlvm/sql.machine.parameters.json'                     # Path to sql parameters file
  lbTemplateFile: 'modules/loadbalancer/lb.json'                                  # Path to lb ARM template file
  lbParametersFile: 'modules/loadbalancer/lb.parameters.json'                     # Path to lb parameters file


stages:
- stage: DeployVNet
  displayName: 'Deploy V-Net'
  jobs:
  - job: DeployResources
    displayName: 'Deploy V-Net & Resources'
    steps:
    - checkout: self  # Ensures code is available on the agent
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureServiceConnection)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(vnetTemplateFile)'
        csmParametersFile: '$(vnetParametersFile)'
        deploymentMode: 'Incremental'
        additionalArguments: '--verbose'

- stage: DeployBastionHost
  displayName: 'Deploy BastionHost'
  jobs:
  - job: DeployResources
    displayName: 'Deploy BastionHost'
    steps:
    - checkout: self  # Ensures code is available on the agent
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureServiceConnection)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(bastionTemplateFile)'
        csmParametersFile: '$(bastionParametersFile)'
        deploymentMode: 'Incremental'
        additionalArguments: '--verbose'

- stage: DeployappMachine
  displayName: 'Deploy appMachine'
  jobs:
  - job: DeployResources
    displayName: 'Deploy appMachine & Resources'
    steps:
    - checkout: self  # Ensures code is available on the agent
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureServiceConnection)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(appMachineTemplateFile)'
        csmParametersFile: '$(appMachineParametersFile)'
        deploymentMode: 'Incremental'
        additionalArguments: '--verbose'

- stage: Deploysql
  displayName: 'Deploy sql'
  jobs:
  - job: DeployResources
    displayName: 'Deploy sql'
    steps:
    - checkout: self  # Ensures code is available on the agent
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureServiceConnection)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(sqlTemplateFile)'
        csmParametersFile: '$(sqlParametersFile)'
        deploymentMode: 'Incremental'
        additionalArguments: '--verbose'


- stage: Deploylb
  displayName: 'Deploy lb'
  jobs:
  - job: DeployResources
    displayName: 'Deploy lb'
    steps:
    - checkout: self  # Ensures code is available on the agent
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureServiceConnection)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(lbTemplateFile)'
        csmParametersFile: '$(lbParametersFile)'
        deploymentMode: 'Incremental'
        additionalArguments: '--verbose'
